# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace '../QuickstartWorkspace'
project 'Core ML Vision Custom.xcodeproj'

target 'Core ML Vision Custom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Core ML Vision Custom
  pod 'IBMWatsonVisualRecognitionV3', '~> 2.0.2'

end
